### ISSUE TITLE
How to solve the problem: hydra. Errors. InstantiationException:

### ISSUE THREAD

**Issue by allllllzxccc** [PinataFarms/FEARTracker#20]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\feartracker\lib\site-packages\hydra\_internal\utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'model_training.model' has no attribute 'fear_net'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\feartracker\lib\site-packages\hydra\_internal\utils.py", line 650, in _locate
    obj = import_module(mod)
  File "D:\Anaconda3\envs\feartracker\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "g:\vot\FEARTracker\model_training\model\fear_net.py", line 6, in <module>
    from model_training.model.blocks import Encoder, AdjustLayer, BoxTower
  File "g:\vot\FEARTracker\model_training\model\blocks.py", line 5, in <module>
    from mobile_cv.model_zoo.models.fbnet_v2 import fbnet
ModuleNotFoundError: No module named 'mobile_cv'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\feartracker\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "D:\Anaconda3\envs\feartracker\lib\site-packages\hydra\_internal\utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'model_training.model.fear_net.FEARNet':
ModuleNotFoundError("No module named 'mobile_cv'")
Are you sure that 'fear_net' is importable from module 'model_training.model'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g:\vot\FEARTracker\demo_video.py", line 62, in <module>
    Fire(main)
  File "D:\Anaconda3\envs\feartracker\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\Anaconda3\envs\feartracker\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\Anaconda3\envs\feartracker\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "g:\vot\FEARTracker\demo_video.py", line 52, in main
    tracker = get_tracker(config_path=config_path, config_name=config_name, weights_path=weights_path)
  File "g:\vot\FEARTracker\demo_video.py", line 16, in get_tracker
    model = instantiate(config["model"])
  File "D:\Anaconda3\envs\feartracker\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "D:\Anaconda3\envs\feartracker\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "D:\Anaconda3\envs\feartracker\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'model_training.model.fear_net.FEARNet', set env var HYDRA_FULL_ERROR=1 to see chained exception.

**Comment by MrCorsair3** [comment]
Change python version to older, e.g. 3.9
